### ISSUE TITLE
ansible galaxy (ansible-core 2.15.5) failing to install role, does not allow symlinks!

### ISSUE THREAD

**Issue by hv15** [willshersystems/ansible-sshd#260]
Hi, since ansible-core 2.15.5 I've been unable to install this role, I get the following error:

```sh
~/ansible-test # ansible-galaxy install -vvvv -fr requirements.yml
ansible-galaxy [core 2.15.5]
  config file = /root/ansible-test/ansible.cfg
  configured module search path = ['/root/ansible-test/library']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/ansible-test/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.9.13 (main, Jun 10 2022, 09:50:06) [GCC] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
Using /root/ansible-test/ansible.cfg as config file
Reading requirement file at '/root/ansible-test/requirements.yml'
found role {'name': 'willshersystems.sshd', 'version': 'v0.18.2', 'scm': None} in yaml file
found role {'name': 'linux-system-roles.timesync', 'version': '1.7.5', 'scm': None} in yaml file
found role {'name': 'linux-system-roles.kdump', 'version': '1.2.9', 'scm': None} in yaml file
Starting galaxy role install process
Processing role willshersystems.sshd
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /root/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v3, pulp-v3, v1' with Galaxy server default (https://galaxy.ansible.com/api/)
- downloading role 'sshd', owned by willshersystems
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/?owner__username=willshersystems&name=sshd
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/30780/versions/?page_size=50
- downloading role from https://github.com/willshersystems/ansible-sshd/archive/v0.18.2.tar.gz
- extracting willshersystems.sshd to /root/ansible-test/roles/willshersystems.sshd
[WARNING]: Illegal filename '..': '..' is not allowed
ERROR! Unexpected Exception, this is probably a bug: join() missing 1 required positional argument: 'a'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 719, in run
    return context.CLIARGS['func']()
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 119, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1370, in execute_install
    self._execute_install_role(role_requirements)
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1469, in _execute_install_role
    installed = role.install()
  File "/usr/local/lib/python3.9/site-packages/ansible/galaxy/role.py", line 426, in install
    setattr(member, attr, os.path.join(*n_final_parts))
TypeError: join() missing 1 required positional argument: 'a'
```

After checking a few things it became clear that this is due to the tar file `v0.18.2.tar.gz` includes a symlink for `..`:

```sh
$ ls -lR ansible-sshd-0.18.2 | grep '^l'
lrwxrwxrwx 1 hans hans 6 Sep 13 15:42 ansible-sshd -> ../../
lrwxrwxrwx 1 hans hans   13 Sep 13 15:42 Fedora_36.yml -> Fedora_37.yml
```

And with ansible-core 2.15.5 symlinks are no longer allowed in roles, see https://github.com/ansible/ansible/blob/v2.15.5/changelogs/CHANGELOG-v2.15.rst#id20.

I have also checked with the latest tar of 0.21.0 and the problem is present there as well.

**Comment by mattwillsher** [comment]
Thanks for the report - I think the link creation can be moved into ci job.

**Comment by nomike** [comment]
Are there plans on creating a new release soon so simple install with `ansible-galaxy install` works again?

**Comment by mattwillsher** [comment]
@nomike yes, when I have some time, or someone else picks it up. Instructions for releasing are in the contribution.md file

**Comment by mattwillsher** [comment]
Currently trying to figure out how to get the v0.22.0 role on Galaxy now NG is the only interface.

**Comment by cecilia-donnelly** [comment]
Same bug here, thank you for working on a fix!

**Comment by mattwillsher** [comment]
The role is now imported, however it is refering the default branch only ('main'), not the version. All version information is missing, though the reason is unknown at the moment. I'm continuing to investigate. Sorry for any inconvience.

**Comment by jeandominiclaroche** [comment]
I don't know if it is related to attempts you did to fix this, but it looks like the role is no longer available through galaxy, even older version. The versions page fails to load

**Comment by mattwillsher** [comment]
This seems to be an issue with Galaxy - the issue is being discussed on the Ansible and other roles imported today seem to have the same problem.

The only work around I can suggest for now is to use the git repo as the src is the requirements as shown above.

**Comment by mattwillsher** [comment]
Fixed Galaxy versions. See #266
